"""empty message

Revision ID: 3d5ea85fc44f
Revises: 33b3645dc7f5
Create Date: 2014-12-28 21:13:07.328787

"""

# revision identifiers, used by Alembic.
revision = '3d5ea85fc44f'
down_revision = '33b3645dc7f5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=30), nullable=False),
    sa.Column('path', sa.Unicode(length=70), nullable=False),
    sa.Column('content', sa.LargeBinary(length=100000), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remote_checkpoints')
    ### end Alembic commands ###
